// <auto-generated />
using System;
using Blackhole.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blackhole.Server.Migrations
{
    [DbContext(typeof(BlackholeDbContext))]
    [Migration("20260129211824_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blackhole.Server.Data.EmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HeaderFrom")
                        .HasColumnType("text");

                    b.Property<string>("HeaderTo")
                        .HasColumnType("text");

                    b.Property<string>("Helo")
                        .HasColumnType("text");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text");

                    b.Property<string>("MailFrom")
                        .HasColumnType("text");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("TextBody")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailFrom");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("Subject");

                    b.ToTable("emails", (string)null);
                });

            modelBuilder.Entity("Blackhole.Server.Data.EmailRecipientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("EmailId");

                    b.ToTable("email_recipients", (string)null);
                });

            modelBuilder.Entity("Blackhole.Server.Data.EmailRecipientEntity", b =>
                {
                    b.HasOne("Blackhole.Server.Data.EmailEntity", "Email")
                        .WithMany("Recipients")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Blackhole.Server.Data.EmailEntity", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
